// ToolHub Beta Phase 6 clean minimal DEX replacement. Rhino ES5.
(function(global){
  if(typeof FloatBallAppWM==="undefined"||!FloatBallAppWM||!FloatBallAppWM.prototype)return;
  if(!global.ShortXUI||global.ShortXUI.__runtimeInstalled!==true)return;
  if(!global.ToolHubBetaPhase6||typeof global.ToolHubBetaPhase6.createBridge!=="function")throw "Phase6 bridge baseline missing";
  var proto=FloatBallAppWM.prototype;
  if(proto.__toolHubShortXUiDexMinimal076Installed===true)return;
  var phase=global.ToolHubBetaPhase6;
  var VERSION="0.7.6-beta-dex-minimal";
  var DEX_SHA256="bb69a0f675d7577f7f4a7f8d2162adfc22226f2c2889be740d166e6a645fb110";
  var DEX_B64="ZGV4CjAzNQA+OP2OG/rf2orM477n4urrS1HPlu38vUmsAQAAcAAAAHhWNBIAAAAAAAAAADABAAAGAAAAcAAAAAMAAACIAAAAAQAAAJQAAAAAAAAAAAAAAAEAAACgAAAAAQAAAKgAAADkAAAAyAAAAMgAAADLAAAA3wAAAPMAAAABAQAACAEAAAEAAAACAAAAAwAAAAAAAAABAAAAAAAAAAIAAAAFAAAAAgAAABEAAAAAAAAAAAAAAP////8AAAAAJgEAAAAAAAABTAASTGphdmEvbGFuZy9PYmplY3Q7ABJMamF2YS9sYW5nL1N0cmluZzsADEx0ZXN0L1Rlc3QxOwAFYmxvcnQABHRlc3QAAAABAAAAAAAAAAAAAAADAAAAGgAEABEAAAABAAAJkAIAAAoAAAAAAAAAAQAAAAAAAAABAAAABgAAAHAAAAACAAAAAwAAAIgAAAADAAAAAQAAAJQAAAAFAAAAAQAAAKAAAAAGAAAAAQAAAKgAAAACIAAABgAAAMgAAAABIAAAAQAAABABAAAAIAAAAQAAACYBAAAAEAAAAQAAADABAAA=";
  function now(){return Number(java.lang.System.currentTimeMillis());}
  function errText(e){try{return String(global.ShortXUI.Core.errorText(e));}catch(x){}try{return String(e);}catch(y){return"unknown";}}
  function log(app,l,m){try{safeLog(app&&app.L,l||"i",String(m||""));}catch(e){}}
  function hex(a){var s="",i,n,h;for(i=0;i<a.length;i+=1){n=Number(a[i]);if(n<0)n+=256;h=n.toString(16);if(h.length<2)h="0"+h;s+=h;}return s;}
  function u32(a,o){var b0=Number(a[o]);if(b0<0)b0+=256;var b1=Number(a[o+1]);if(b1<0)b1+=256;var b2=Number(a[o+2]);if(b2<0)b2+=256;var b3=Number(a[o+3]);if(b3<0)b3+=256;return b0+b1*256+b2*65536+b3*16777216;}
  function parentLoader(){var l=null;try{l=context.getClassLoader();}catch(e0){}try{if(!l)l=java.lang.Thread.currentThread().getContextClassLoader();}catch(e1){}try{if(!l)l=java.lang.ClassLoader.getSystemClassLoader();}catch(e2){}return l;}
  function jClassArray(a){var s=a||[],o=java.lang.reflect.Array.newInstance(java.lang.Class,s.length),i;for(i=0;i<s.length;i+=1)o[i]=s[i];return o;}
  function jObjectArray(a){var s=a||[],o=java.lang.reflect.Array.newInstance(java.lang.Object,s.length),i;for(i=0;i<s.length;i+=1)o[i]=s[i];return o;}
  function causeOf(e){var t=null,c=null;try{t=e&&e.javaException?e.javaException:e;}catch(x){t=e;}try{if(t&&t instanceof java.lang.reflect.InvocationTargetException)c=t.getCause();}catch(y){}if(!c)c=t;var n="",m="";try{if(c&&c.getClass)n=String(c.getClass().getName());}catch(a){}try{if(c&&c.getMessage)m=String(c.getMessage()||"");}catch(b){}return{className:n||"unknown",message:m||errText(e)};}
  function probe(){
    var r={ok:false,code:"UNAVAILABLE",loaderClass:"",loadedClass:"",method:"test",result:"",parentDelegation:false,dexLoaded:false,dexBytes:0,dexSha256:"",expectedSha256:DEX_SHA256,bufferDirect:false,bufferPosition:0,bufferLimit:0,bufferCapacity:0,header:null,error:""};
    try{
      var bytes=android.util.Base64.decode(DEX_B64,android.util.Base64.NO_WRAP);r.dexBytes=Number(bytes.length);
      var md=java.security.MessageDigest.getInstance("SHA-256");md.update(bytes,0,bytes.length);r.dexSha256=hex(md.digest());
      if(r.dexSha256!==DEX_SHA256){r.code="MINIMAL_DEX_HASH_MISMATCH";return r;}
      var magic="",i,n;for(i=0;i<8;i+=1){n=Number(bytes[i]);if(n<0)n+=256;magic+=String.fromCharCode(n);}
      var sha1=java.security.MessageDigest.getInstance("SHA-1");sha1.update(bytes,32,bytes.length-32);var sig=hex(sha1.digest());var hs="";for(i=12;i<32;i+=1){n=Number(bytes[i]);if(n<0)n+=256;var h=n.toString(16);if(h.length<2)h="0"+h;hs+=h;}
      var ad=new java.util.zip.Adler32();ad.update(bytes,12,bytes.length-12);var checksum=Number(ad.getValue())>>>0;var headerChecksum=u32(bytes,8)>>>0;
      var text=String(new java.lang.String(bytes,"ISO-8859-1"));
      r.header={magic:magic,fileSize:u32(bytes,32),headerSize:u32(bytes,36),endian:u32(bytes,40)>>>0,mapOff:u32(bytes,52),stringCount:u32(bytes,56),typeCount:u32(bytes,64),protoCount:u32(bytes,72),methodCount:u32(bytes,88),classCount:u32(bytes,96),signature:hs,signatureValid:hs===sig,checksum:("00000000"+headerChecksum.toString(16)).slice(-8),checksumValid:headerChecksum===checksum,containsClass:text.indexOf("Ltest/Test1;")>=0,containsMethod:text.indexOf("test")>=0,containsResult:text.indexOf("blort")>=0};
      if(magic!=="dex\n035\u0000"||r.header.fileSize!==bytes.length||r.header.headerSize!==112||r.header.endian!==0x12345678||!r.header.signatureValid||!r.header.checksumValid||r.header.classCount!==1||r.header.methodCount!==1||!r.header.containsClass||!r.header.containsResult){r.code="MINIMAL_DEX_STRUCTURE_INVALID";return r;}
      var buffer=java.nio.ByteBuffer.allocateDirect(bytes.length);buffer.put(bytes,0,bytes.length);buffer.flip();r.bufferDirect=buffer.isDirect()===true;r.bufferPosition=Number(buffer.position());r.bufferLimit=Number(buffer.limit());r.bufferCapacity=Number(buffer.capacity());
      if(!r.bufferDirect||r.bufferPosition!==0||r.bufferLimit!==bytes.length){r.code="DIRECT_BUFFER_STATE_INVALID";return r;}
      var lc=java.lang.Class.forName("dalvik.system.InMemoryDexClassLoader"),bb=java.lang.Class.forName("java.nio.ByteBuffer"),cl=java.lang.Class.forName("java.lang.ClassLoader"),ct=lc.getConstructor(jClassArray([bb,cl])),ld=ct.newInstance(jObjectArray([buffer,parentLoader()])),loaded=ld.loadClass("test.Test1"),m=loaded.getMethod("test",jClassArray([])),value=m.invoke(null,jObjectArray([])),parent=ld.loadClass("java.lang.String");
      r.loaderClass=String(ld.getClass().getName());r.loadedClass=String(loaded.getName());r.result=String(value);r.parentDelegation=String(parent.getName())==="java.lang.String";r.dexLoaded=true;r.ok=r.loadedClass==="test.Test1"&&r.result==="blort"&&r.parentDelegation;r.code=r.ok?"EMBEDDED_DEX_OK":"EMBEDDED_DEX_RESULT_INVALID";
    }catch(e){var c=causeOf(e);r.code="IN_MEMORY_DEX_FAILED";r.error=c.className+": "+c.message;}
    return r;
  }
  function capability(){var im=false,dx=false;try{im=java.lang.Class.forName("dalvik.system.InMemoryDexClassLoader")!==null;}catch(e0){}try{dx=java.lang.Class.forName("dalvik.system.DexClassLoader")!==null;}catch(e1){}return{ok:!!(global.ShortXUI&&global.ShortXUI.Core&&parentLoader()),runtimeVersion:String(global.ShortXUI.VERSION||""),hasClassLoader:parentLoader()!==null,hasReflection:true,hasInMemoryDexClassLoader:im,hasDexClassLoader:dx,embeddedTestDexEnabled:true,minimalDexGenerated:true,minimalDexBytes:428,minimalDexSha256:DEX_SHA256,externalDexPayloadEnabled:false,sdk:Number(android.os.Build.VERSION.SDK_INT),wrapperVersion:VERSION};}
  function persist(app){var w=null,t=null;try{if(!app||!app.state)return false;var root="";try{if(typeof getToolHubRootDir==="function")root=String(getToolHubRootDir()||"");}catch(e0){}if(!root&&typeof APP_ROOT_DIR!=="undefined")root=String(APP_ROOT_DIR||"");if(!root)return false;var f=new java.io.File(root+"/diagnostics/shortx-ui/latest.json"),p=f.getParentFile();if(p&&!p.exists()&&!p.mkdirs()&&!p.exists())return false;t=new java.io.File(f.getAbsolutePath()+".tmp");var s=app.state,c=capability(),o={schema:7,runtimeVersion:c.runtimeVersion,wrapperVersion:VERSION,ok:c.ok&&!(s.shortXUiDexLastResult&&s.shortXUiDexLastResult.ok===false)&&!(s.shortXUiDexStressResult&&s.shortXUiDexStressResult.ok===false),savedAt:now(),capability:c,basic:s.shortXUiLabLastResult||null,dispatcher:s.shortXUiLabLastDispatcherResult||null,windowHost:s.shortXUiLabLastWindowResult||null,windowStress:s.shortXUiLabLastWindowStressResult||null,imeFocus:s.shortXUiImeLastResult||null,imeStress:s.shortXUiImeStressResult||null,gesture:s.shortXUiGestureLastResult||null,gestureStress:s.shortXUiGestureStressResult||null,canvas:s.shortXUiCanvasLastResult||null,canvasStress:s.shortXUiCanvasStressResult||null,dexBridge:s.shortXUiDexLastResult||null,dexStress:s.shortXUiDexStressResult||null};w=new java.io.OutputStreamWriter(new java.io.FileOutputStream(t,false),"UTF-8");w.write(JSON.stringify(o,null,2)+"\n");w.flush();w.close();w=null;if(f.exists()&&!f.delete())throw"replace failed";if(!t.renameTo(f))throw"publish failed";return true;}catch(e){log(app,"w","ShortXUI minimal DEX diagnostics save failed: "+errText(e));return false;}finally{try{if(w)w.close();}catch(x){}try{if(t&&t.exists())t.delete();}catch(y){}}}
  function format(app){var c=capability(),r=app&&app.state?app.state.shortXUiDexLastResult:null,s=app&&app.state?app.state.shortXUiDexStressResult:null,l=[];l.push("DEX Bridge + 最小 DEX："+(c.ok?"可用":"不可用"));l.push("SDK="+c.sdk+" bytes="+c.minimalDexBytes+" sha="+c.minimalDexSha256.substring(0,12));l.push("外部 DEX 载荷=false");if(r)l.push("基线="+(r.ok?"通过":"失败")+" checks="+r.passed+"/"+r.total+" dex="+(r.inMemory&&r.inMemory.code));else l.push("基线=尚未运行");if(s){l.push("");l.push("压力测试="+(s.running?"运行中":(s.ok?"通过":"失败")));l.push("cycles="+s.cyclesCompleted+"/"+s.cyclesRequested+" invoke="+s.invocations+" cache="+s.cacheHits);l.push("dispose="+s.disposePasses+" mapping="+s.errorMappingPasses+" dex="+s.embeddedDexPasses+" errors="+s.errors);}return l.join("\n");}
  function refresh(app){if(!app||!app.state||!app.state.shortXUiDexStatusView)return;var v=app.state.shortXUiDexStatusView;try{new android.os.Handler(android.os.Looper.getMainLooper()).post(new java.lang.Runnable({run:function(){try{v.setText(format(app));}catch(e){}}}));}catch(x){}}
  function ck(a,n,ok,d){a.push({name:String(n),ok:ok===true,detail:d||null});}
  proto.runShortXUiDexBaseline=function(){if(!this.state)this.state={};var start=now(),a=[],b=phase.createBridge(),c1=b.resolveClass("java.lang.StringBuilder"),c2=b.resolveClass("java.lang.StringBuilder");ck(a,"class-cache",c1.ok&&c2.ok,{first:c1.code,second:c2.code});var o=b.newInstance("java.lang.StringBuilder",[],[]);ck(a,"constructor",o.ok,{code:o.code});var x=o.ok?b.invokeInstance(o.value,"java.lang.StringBuilder","append",["java.lang.String"],[new java.lang.String("bridge-")]):{ok:false},y=o.ok?b.invokeInstance(o.value,"java.lang.StringBuilder","append",["int"],[java.lang.Integer.valueOf(42)]):{ok:false},z=o.ok?b.invokeInstance(o.value,"java.lang.StringBuilder","toString",[],[]):{ok:false};ck(a,"instance-overload",x.ok&&y.ok&&z.ok&&String(z.value)==="bridge-42",{value:z.ok?String(z.value):""});var p=b.invokeStatic("java.lang.Integer","parseInt",["java.lang.String"],[new java.lang.String("73")]);ck(a,"static-primitive",p.ok&&Number(p.value)===73,{value:p.ok?Number(p.value):null});var m=b.invokeStatic("java.lang.Math","max",["int","int"],[java.lang.Integer.valueOf(7),java.lang.Integer.valueOf(11)]);ck(a,"static-overload",m.ok&&Number(m.value)===11,{value:m.ok?Number(m.value):null});var bad=b.invokeStatic("java.lang.Integer","parseInt",["java.lang.String"],[new java.lang.String("bad")]);ck(a,"exception-mapping",!bad.ok&&bad.code==="INVOCATION_FAILED"&&String(bad.causeClass||"").indexOf("NumberFormatException")>=0,{code:bad.code,cause:bad.causeClass});var miss=b.resolveMethod("java.lang.Math","missingMethod",[],true);ck(a,"missing-method",!miss.ok&&miss.code==="METHOD_NOT_FOUND",{code:miss.code});var deny=b.resolveClass("java.io.File");ck(a,"allowlist",!deny.ok&&deny.code==="CLASS_NOT_ALLOWED",{code:deny.code});var im=probe();ck(a,"embedded-in-memory-dex",im.ok,im);var before=b.snapshot(),d=b.dispose(),after=b.resolveClass("java.lang.String");ck(a,"dispose",d===true&&!after.ok&&after.code==="BRIDGE_DISPOSED",{code:after.code});var pass=0,i;for(i=0;i<a.length;i+=1)if(a[i].ok)pass+=1;var r={schema:1,runtimeVersion:String(global.ShortXUI.VERSION||""),wrapperVersion:VERSION,ok:pass===a.length,startedAt:start,finishedAt:now(),durationMs:Math.max(0,now()-start),passed:pass,total:a.length,checks:a,inMemory:im,bridge:before,postDispose:b.snapshot()};this.state.shortXUiDexLastResult=r;persist(this);refresh(this);log(this,r.ok?"i":"e","DEX_BRIDGE_BASELINE_MINIMAL ok="+r.ok+" passed="+pass+"/"+a.length+" code="+im.code);return r;};
  proto.runShortXUiDexStress=function(){if(!this.state)this.state={};var start=now(),cycles=[],totalInv=0,totalCache=0,disposePasses=0,mapPasses=0,errors=0,i,j;for(i=0;i<20;i+=1){var b=phase.createBridge(),ok=true,inv=0;for(j=0;j<50;j+=1){var q=b.invokeStatic("java.lang.Math","max",["int","int"],[java.lang.Integer.valueOf(j),java.lang.Integer.valueOf(j+1)]);if(!q.ok||Number(q.value)!==j+1){ok=false;break;}inv+=1;}var bad=b.invokeStatic("java.lang.Integer","parseInt",["java.lang.String"],[new java.lang.String("bad")]),mapping=!bad.ok&&String(bad.causeClass||"").indexOf("NumberFormatException")>=0,snap=b.snapshot(),disposed=b.dispose()===true;if(mapping)mapPasses+=1;if(disposed)disposePasses+=1;totalInv+=inv;totalCache+=Number(snap.stats&&snap.stats.methodCacheHits||0);if(!ok||!mapping||!disposed)errors+=1;cycles.push({index:i+1,ok:ok&&mapping&&disposed,invocations:inv,cacheHits:Number(snap.stats&&snap.stats.methodCacheHits||0),dispose:disposed,errorMapping:mapping});}var im=probe();if(!im.ok)errors+=1;var r={schema:3,runtimeVersion:String(global.ShortXUI.VERSION||""),wrapperVersion:VERSION,ok:errors===0&&totalInv===1000&&disposePasses===20&&mapPasses===20&&im.ok,running:false,startedAt:start,finishedAt:now(),durationMs:Math.max(0,now()-start),cyclesRequested:20,cyclesCompleted:20,invocationsRequested:1000,invocations:totalInv,cacheHits:totalCache,disposePasses:disposePasses,errorMappingPasses:mapPasses,embeddedDexPasses:im.ok?1:0,embeddedDex:im,errors:errors,cycles:cycles};this.state.shortXUiDexStressResult=r;persist(this);refresh(this);log(this,r.ok?"i":"e","DEX_BRIDGE_STRESS_MINIMAL ok="+r.ok+" completed=20/20 dex="+r.embeddedDexPasses+" errors="+errors+" code="+im.code);return r;};
  phase.VERSION=VERSION;phase.MINIMAL_VERSION=VERSION;phase.MINIMAL_DEX_SHA256=DEX_SHA256;phase.MINIMAL_DEX_BYTES=428;phase.probeEmbeddedDex=probe;phase.getCapability=capability;
  proto.__toolHubShortXUiDexMinimal076Installed=true;
  try{log(null,"i","ShortXUI minimal DEX replacement installed version="+VERSION+" sha256="+DEX_SHA256);}catch(e){}
})(this);
