#!/usr/bin/env python3
"""Finalize the verified ShortXUI beta chain into one signed runtime package."""
from __future__ import annotations

import argparse
import base64
import gzip
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENTRY = ROOT / "ToolHub.js"
MANIFEST_GENERATOR = ROOT / "scripts" / "generate_signed_manifest.py"
PREPARE_CONSTRAINTS = ROOT / "scripts" / "prepare_shortx_ui_constraints.py"
BOUNDARIES = ROOT / "constraints" / "MODULE_BOUNDARIES.json"
API_RULES = ROOT / "constraints" / "api.json"
PROTECTED_REPORTER = ROOT / "scripts" / "report_protected_wrapper_chains.py"
ARCHITECTURE = ROOT / "docs" / "ARCHITECTURE.md"
STRUCTURE = ROOT / "docs" / "STRUCTURE.md"
LEGACY_FINAL_ENTRY = ROOT / "ToolHub-beta-final.js"
VERIFY_WORKFLOW = ROOT / ".github" / "workflows" / "verify.yml"
SIGN_WORKFLOW = ROOT / ".github" / "workflows" / "sign-toolhub.yml"
SCRIPTS_README = ROOT / "scripts" / "README.md"
OUTPUT = ROOT / "code" / "th_25_shortx_ui_package.js"

PACKAGE_MODULE = "th_25_shortx_ui_package.js"
PACKAGE_VERSION = "0.9.2"
ENTRY_VERSION = 20260809223000

PAYLOADS = [
    "beta/phase2/shortxui_guard.js",
    "beta/phase2/windowhost_hardening.js",
    "beta/phase3/ime_focus_lab.js",
    "beta/phase3/ime_focus_rearm_patch.js",
    "beta/phase4/gesture_back_lab.js",
    "beta/phase4/gesture_system_close_patch.js",
    "beta/phase5/canvas_frame_lab.js",
    "beta/phase6/dex_bridge_lab.js",
    "beta/phase6/dex_minimal_replacement.js",
    "beta/phase7/shortxui_api_facade_lab.js",
    "beta/phase7/shortxui_phase7b_components.js",
    "beta/phase7/phase7b_latest_reconcile_patch.js",
    "beta/phase7/shortxui_phase7c_route_integration.js",
    "beta/phase7/phase7c_lifecycle_r2_patch.js",
    "beta/final/shortxui_final_acceptance.js",
    "beta/final/final_acceptance_r2_patch.js",
    "beta/final/final_acceptance_r3_dismiss_patch.js",
]


def fail(message: str) -> None:
    raise SystemExit("FAIL: " + message)


def read_text(path: Path) -> str:
    if not path.exists():
        fail("missing " + str(path.relative_to(ROOT)))
    return path.read_text(encoding="utf-8")


def write_or_check(path: Path, expected: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if current == expected:
        return False
    if check:
        fail("generated file is stale: " + str(path.relative_to(ROOT)))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    return True


def replace_once(text: str, source: str, target: str, label: str) -> str:
    if target in text:
        return text
    if source not in text:
        fail(label + " anchor missing")
    return text.replace(source, target, 1)


def js_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True, separators=(",", ":"))


def chunk_text(value: str, width: int = 120) -> list[str]:
    return [value[index:index + width] for index in range(0, len(value), width)]


def build_package() -> str:
    payload_rows = []
    source_manifest = []
    for rel in PAYLOADS:
        path = ROOT / rel
        raw = path.read_bytes()
        digest = hashlib.sha256(raw).hexdigest()
        packed_bytes = bytearray(gzip.compress(raw, compresslevel=9, mtime=0))
        if len(packed_bytes) > 9:
            packed_bytes[9] = 255
        packed = bytes(packed_bytes)
        encoded = base64.b64encode(packed).decode("ascii")
        chunks = ",\n        ".join(js_string(chunk) for chunk in chunk_text(encoded))
        payload_rows.append(
            "    {\n"
            "      name: %s,\n"
            "      sha256: %s,\n"
            "      data: [\n        %s\n      ].join(\"\")\n"
            "    }" % (js_string(rel), js_string(digest), chunks)
        )
        source_manifest.append({"name": rel, "sha256": digest, "bytes": len(raw)})

    manifest_json = json.dumps(source_manifest, ensure_ascii=False, separators=(",", ":"))
    manifest_sha = hashlib.sha256(manifest_json.encode("utf-8")).hexdigest()
    rows = ",\n".join(payload_rows)

    return '''// @version __PACKAGE_VERSION__
// ToolHub Beta ShortXUI verified runtime package.
// Generated by scripts/finalize_shortx_ui_runtime.py; do not edit by hand.
// Installs the accepted Phase 2 -> Final R3 chain only after startAsync succeeds.
(function (global) {
  if (typeof FloatBallAppWM === "undefined" || !FloatBallAppWM || !FloatBallAppWM.prototype) {
    throw "ShortXUI package requires FloatBallAppWM";
  }

  var PACKAGE_VERSION = "__PACKAGE_VERSION__";
  var PACKAGE_MANIFEST_SHA256 = "__MANIFEST_SHA__";
  var PAYLOADS = [
__PAYLOAD_ROWS__
  ];
  var proto = FloatBallAppWM.prototype;
  var state = global.__ToolHubShortXUiPackageState;
  if (!state || String(state.version || "") !== PACKAGE_VERSION) {
    state = {
      version: PACKAGE_VERSION,
      installed: false,
      installing: false,
      prototypeRef: null,
      installCount: 0,
      lastAt: 0,
      lastError: ""
    };
    global.__ToolHubShortXUiPackageState = state;
  }

  function closeQuietly(resource) {
    try { if (resource) resource.close(); } catch (e) {}
  }

  function toHex(bytes) {
    var out = "";
    var i;
    for (i = 0; i < bytes.length; i += 1) {
      var value = Number(bytes[i]);
      if (value < 0) value += 256;
      var part = value.toString(16);
      if (part.length < 2) part = "0" + part;
      out += part;
    }
    return out;
  }

  function decodeVerified(item) {
    var byteInput = null;
    var gzipInput = null;
    var output = null;
    try {
      var compressed = android.util.Base64.decode(String(item.data || ""), android.util.Base64.DEFAULT);
      byteInput = new java.io.ByteArrayInputStream(compressed);
      gzipInput = new java.util.zip.GZIPInputStream(byteInput);
      output = new java.io.ByteArrayOutputStream();
      var digest = java.security.MessageDigest.getInstance("SHA-256");
      var buffer = java.lang.reflect.Array.newInstance(java.lang.Byte.TYPE, 8192);
      var total = 0;
      var count;
      while ((count = gzipInput.read(buffer)) !== -1) {
        if (count <= 0) continue;
        total += count;
        if (total > 2 * 1024 * 1024) throw String(item.name) + " exceeds unpacked size limit";
        output.write(buffer, 0, count);
        digest.update(buffer, 0, count);
      }
      var actual = toHex(digest.digest());
      if (actual !== String(item.sha256 || "")) {
        throw String(item.name) + " packaged SHA-256 mismatch: " + actual;
      }
      return String(new java.lang.String(output.toByteArray(), "UTF-8"));
    } finally {
      closeQuietly(gzipInput);
      closeQuietly(byteInput);
      closeQuietly(output);
    }
  }

  function verifyFinalState() {
    if (typeof ToolHubBetaFinalR3 === "undefined" ||
        String(ToolHubBetaFinalR3.VERSION || "") !== "0.9.2-beta-final-dismiss-fix" ||
        ToolHubBetaFinalR3.IME_BACK_ROUTES_THROUGH_TOOLAPP !== true ||
        ToolHubBetaFinalR3.IME_CLOSE_ON_HOME_RECENTS !== true ||
        ToolHubBetaFinalR3.KEY_FALLBACK_ENABLED !== true ||
        ToolHubBetaFinalR3.DIAGNOSTICS_RECONCILE_AFTER_IME !== true ||
        ToolHubBetaFinalR3.EXTERNAL_DEX_PAYLOAD_ENABLED !== false) {
      throw "ShortXUI packaged final R3 verification failed";
    }
    if (typeof ShortXUI === "undefined" ||
        String(ShortXUI.VERSION || "") !== "0.2.0" ||
        String(ShortXUI.API_VERSION || "") !== "0.4.0-beta" ||
        !ShortXUI.API || !ShortXUI.ImeController || !ShortXUI.BackController) {
      throw "ShortXUI packaged public API verification failed";
    }
    var dexCheck = ShortXUI.API.createDexBridge({});
    if (!dexCheck || dexCheck.ok !== false || String(dexCheck.code || "") !== "EXTERNAL_DEX_DISABLED") {
      throw "ShortXUI packaged external DEX boundary verification failed";
    }
    return true;
  }

  function install(app) {
    if (state.installing === true) throw "ShortXUI package installation re-entry";
    if (state.installed === true && state.prototypeRef === FloatBallAppWM.prototype) {
      return {
        ok: true,
        alreadyInstalled: true,
        version: PACKAGE_VERSION,
        payloads: PAYLOADS.length
      };
    }

    state.installing = true;
    state.lastError = "";
    try {
      var globalEval = eval;
      var index;
      for (index = 0; index < PAYLOADS.length; index += 1) {
        var item = PAYLOADS[index];
        var source = decodeVerified(item);
        try { writeLog("ShortXUI package payload verified " + String(item.name)); } catch (eLogBefore) {}
        globalEval(String(source));
      }
      verifyFinalState();
      state.installed = true;
      state.prototypeRef = FloatBallAppWM.prototype;
      state.installCount = Number(state.installCount || 0) + 1;
      state.lastAt = Number(java.lang.System.currentTimeMillis());
      global.ToolHubShortXUiPackage = {
        VERSION: PACKAGE_VERSION,
        PAYLOAD_COUNT: PAYLOADS.length,
        MANIFEST_SHA256: PACKAGE_MANIFEST_SHA256,
        INSTALL_AFTER_START: true,
        FINAL_R3: true,
        EXTERNAL_DEX_PAYLOAD_ENABLED: false,
        installed: true
      };
      try {
        writeLog(
          "ShortXUI package ready version=" + PACKAGE_VERSION +
          " payloads=" + String(PAYLOADS.length) +
          " finalR3=true installAfterStart=true dexExternal=false"
        );
      } catch (eLogReady) {}
      return {
        ok: true,
        version: PACKAGE_VERSION,
        payloads: PAYLOADS.length,
        manifestSha256: PACKAGE_MANIFEST_SHA256
      };
    } catch (error) {
      state.installed = false;
      state.prototypeRef = null;
      state.lastError = String(error);
      try { writeLog("ShortXUI package install failed: " + String(error)); } catch (eLogFail) {}
      throw error;
    } finally {
      state.installing = false;
    }
  }

  var oldStartAsyncShortXUiPackage = proto.startAsync;
  if (typeof oldStartAsyncShortXUiPackage !== "function") throw "ShortXUI package requires startAsync";
  if (oldStartAsyncShortXUiPackage.__toolHubShortXUiPackageWrapped !== true) {
    proto.startAsync = function (entryInfo, closeRule) {
      var result = oldStartAsyncShortXUiPackage.call(this, entryInfo, closeRule);
      if (!result || result.ok !== true) return result;
      try {
        var packageResult = install(this);
        result.shortXUiPackage = packageResult;
        return result;
      } catch (error) {
        try { if (this && typeof this.close === "function") this.close(); } catch (eClose) {}
        return {
          ok: false,
          started: false,
          err: "ShortXUI package install failed: " + String(error),
          shortXUiPackage: {
            ok: false,
            version: PACKAGE_VERSION,
            error: String(error)
          }
        };
      }
    };
    proto.startAsync.__toolHubShortXUiPackageWrapped = true;
  }

  global.ToolHubShortXUiPackage = {
    VERSION: PACKAGE_VERSION,
    PAYLOAD_COUNT: PAYLOADS.length,
    MANIFEST_SHA256: PACKAGE_MANIFEST_SHA256,
    INSTALL_AFTER_START: true,
    FINAL_R3: true,
    EXTERNAL_DEX_PAYLOAD_ENABLED: false,
    installed: state.installed === true
  };
}(function () { return this; }()));
'''.replace("__PACKAGE_VERSION__", PACKAGE_VERSION).replace(
        "__MANIFEST_SHA__", manifest_sha
    ).replace("__PAYLOAD_ROWS__", rows)


def patch_entry(text: str) -> str:
    text = re.sub(
        r"var TOOLHUB_ENTRY_VERSION = \d+;",
        "var TOOLHUB_ENTRY_VERSION = %d;" % ENTRY_VERSION,
        text,
        count=1,
    )
    required = (
        ("var TOOLHUB_STABLE_MODULES = [", "stable module set"),
        ('"th_25_shortx_ui_package.js"];', "beta package module"),
        ("function refreshToolHubChannelModuleSet(channel)", "channel module selector"),
        ("refreshToolHubChannelModuleSet(normalized);", "runtime channel refresh"),
        ('criticalModules["th_25_shortx_ui_package.js"] = true;', "beta critical module"),
    )
    for marker, label in required:
        if marker not in text:
            fail(label + " missing from ToolHub.js")
    return text


def patch_manifest_generator(text: str) -> str:
    source = '    "th_23_screenshot_manager.js",\n]'
    target = '    "th_23_screenshot_manager.js", "th_25_shortx_ui_package.js",\n]'
    return replace_once(text, source, target, "manifest module list")


def patch_prepare_constraints(text: str) -> str:
    source = '    "code/th_34_shortx_ui_lab.js",\n}'
    target = '    "code/th_34_shortx_ui_lab.js",\n    "code/th_25_shortx_ui_package.js",\n}'
    return replace_once(text, source, target, "ShortXUI constraint scope")


def patch_api_rules(text: str) -> str:
    from report_api_usage import scan_repository

    phase_files = {
        "code/th_24_shortx_ui_runtime.js",
        "code/th_34_shortx_ui_lab.js",
        "code/th_25_shortx_ui_package.js",
    }
    unused_files, entries = scan_repository(ROOT)
    phase_entries = [
        item for item in entries
        if phase_files.intersection(set(item.get("files") or []))
    ]
    if not phase_entries:
        fail("ShortXUI packaged API usage was not detected")
    usage_keys = sorted({str(item.get("key", "")) for item in phase_entries if str(item.get("key", ""))})
    scope = sorted({
        str(file_name)
        for item in phase_entries
        for file_name in (item.get("files") or [])
        if str(file_name)
    })

    data = json.loads(text)
    rules = list(data.get("rules") or [])
    found = False
    for rule in rules:
        if str(rule.get("id", "")) != "api-shortx-ui-beta-phase1":
            continue
        rule["usageKeys"] = usage_keys
        rule["scope"] = scope
        rule["classOrObject"] = "ShortXUI final package dependency set"
        rule["owner"] = "ShortXUI Beta runtime, final package and ToolHub adapter"
        rule["guard"] = "ToolHub runtime minimum API is 33; WindowMetrics and WindowInsets retain platform guards; the final package installs only after startAsync succeeds"
        rule["threadContract"] = "WindowHost work stays on the supplied Dispatcher; final package decoding runs on the ShortX task thread after startup confirmation; View operations keep their existing Android Main/ToolHub WM ownership"
        rule["fallback"] = "Any packaged source hash, install or final-state verification failure closes the current ToolHub instance and returns startup failure; Stable excludes all ShortXUI Beta modules"
        rule["reason"] = "登记 Beta 最终封装及基础运行时实际使用的精确 Android/Java API，锁定 Phase 2 至 Final R3 的启动后安装边界"
        found = True
        break
    if not found:
        fail("ShortXUI API classification rule missing")
    data["rules"] = rules
    return json.dumps(data, ensure_ascii=False, indent=2) + "\n"


def patch_boundaries(text: str) -> str:
    data = json.loads(text)
    records = list(data.get("duplicateDefinitions") or [])
    record = {
        "method": "startAsync",
        "definitions": ["th_16_entry.js", "th_25_shortx_ui_package.js"],
        "effectiveOwner": "th_25_shortx_ui_package.js",
        "type": "wrapper",
        "reason": "在悬浮球启动成功后安装经真机验收的 ShortXUI 最终 R3 封装，保持原测试时序并将失败回传为启动失败",
        "wrappers": [
            {
                "module": "th_25_shortx_ui_package.js",
                "owner": "th_16_entry.js",
                "oldVariable": "oldStartAsyncShortXUiPackage",
            }
        ],
    }
    records = [item for item in records if item.get("method") != "startAsync"]
    records.append(record)
    records.sort(key=lambda item: str(item.get("method", "")))
    data["duplicateDefinitions"] = records
    return json.dumps(data, ensure_ascii=False, indent=2) + "\n"


def patch_protected_reporter(text: str) -> str:
    if '    "ShortXUI 最终封装": 6,' not in text:
        text = replace_once(
            text,
            '    "Beta 实验扩展": 5,\n',
            '    "Beta 实验扩展": 5,\n    "ShortXUI 最终封装": 6,\n',
            "protected category",
        )
    if '    "startAsync": (' not in text:
        anchor = '    "isToolAppRoute": (\n        "Beta 实验扩展",\n        "继续保留",\n        "只登记实验室路由，其他路由识别继续委托原实现。",\n    ),\n'
        addition = anchor + (
            '    "startAsync": (\n'
            '        "ShortXUI 最终封装",\n'
            '        "继续保留",\n'
            '        "原启动成功后再安装已验收 R3 能力；封装失败会关闭实例并返回启动失败。",\n'
            '    ),\n'
        )
        text = replace_once(text, anchor, addition, "protected startAsync classification")
    if '        "ShortXUI 最终封装": "继续保留，属于验收封装与失败回滚边界",' not in text:
        text = replace_once(
            text,
            '        "Beta 实验扩展": "继续保留，仅在 Beta 实验室路由生效",\n',
            '        "Beta 实验扩展": "继续保留，仅在 Beta 实验室路由生效",\n'
            '        "ShortXUI 最终封装": "继续保留，属于验收封装与失败回滚边界",\n',
            "protected category decision",
        )
    return text


def patch_architecture(text: str) -> str:
    text = text.replace("更新时间：2026-07-27", "更新时间：2026-07-28", 1)
    text = text.replace("31 个子模块", "32 个子模块")
    source = "  th_23_screenshot_manager.js\n```"
    target = (
        "  th_23_screenshot_manager.js\n\n"
        "最终封装层\n"
        "  th_25_shortx_ui_package.js\n```"
    )
    text = replace_once(text, source, target, "architecture module list")
    responsibility_source = (
        "th_24_shortx_ui_runtime.js\n"
        "  Beta 隔离的 ShortXUI 第一阶段基础运行时，提供 Core、Dispatcher、Scope、Color、Metrics、Display、Shape 和 Diagnostics；颜色操作通过已验证的 ToolHub 安全桥注入，不接管正式 UI。\n\n"
        "th_03_icon.js"
    )
    responsibility_target = (
        "th_24_shortx_ui_runtime.js\n"
        "  Beta 隔离的 ShortXUI 第一阶段基础运行时，提供 Core、Dispatcher、Scope、Color、Metrics、Display、Shape 和 Diagnostics；颜色操作通过已验证的 ToolHub 安全桥注入，不接管正式 UI。\n\n"
        "th_25_shortx_ui_package.js\n"
        "  Beta 最终 ShortXUI 封装模块。保存 Phase 2 至 Final R3 的确定性压缩源码和逐项 SHA-256，仅在 `startAsync()` 成功后按已验收顺序安装；安装失败立即关闭当前实例并返回启动失败。\n\n"
        "th_03_icon.js"
    )
    text = replace_once(text, responsibility_source, responsibility_target, "architecture package responsibility")
    boundary = (
        "th_34_shortx_ui_lab.js\n"
        "  Beta 专用 ShortX UI 实验室 ToolApp 页面，提供基础环境、颜色、Shape 与 Android Main/ToolHub WM Dispatcher 自检；"
        "实验异常不替换悬浮球、主面板、WindowManager、IME、Canvas、指针或 OCR 路径。"
    )
    if boundary in text:
        text = text.replace(
            boundary,
            "th_34_shortx_ui_lab.js\n"
            "  Beta 专用 ShortX UI 实验室 ToolApp 页面，保留基础环境、线程、WindowHost 和最终验收诊断入口；"
            "正式 IME、返回、Canvas、API 与生命周期能力由 `th_25_shortx_ui_package.js` 在启动成功后统一安装。",
            1,
        )
    return text


def patch_structure(text: str) -> str:
    text = text.replace("更新时间：2026-07-27", "更新时间：2026-07-28", 1)
    text = text.replace("31 个子模块", "32 个子模块")
    text = text.replace("files: 31 个模块", "files: 32 个模块")
    source = "│   └── th_23_screenshot_manager.js"
    target = "│   ├── th_23_screenshot_manager.js\n│   └── th_25_shortx_ui_package.js"
    text = replace_once(text, source, target, "structure tree")
    source = (
        "Beta 第一阶段额外加载 `th_24_shortx_ui_runtime.js` 与 `th_34_shortx_ui_lab.js`。"
        "两者运行在 `ToolHub-Beta` 隔离根目录，实验诊断写入 `diagnostics/shortx-ui/`；"
        "Stable 和 ClipHub 不读取这些实验状态。"
    )
    target = (
        "Beta 通道额外加载 `th_24_shortx_ui_runtime.js`、`th_34_shortx_ui_lab.js` 与 "
        "`th_25_shortx_ui_package.js`。前两者提供基础运行时和诊断入口，最终封装模块在 "
        "`startAsync()` 成功后安装 Phase 2 至 Final R3 的已验收能力；全部状态位于 "
        "`ToolHub-Beta` 隔离根目录，Stable 和 ClipHub 不读取这些实验状态。"
    )
    text = replace_once(text, source, target, "structure beta description")
    source = "│   ├── th_23_screenshot_manager.js\n│   ├── .installed_manifest.json"
    target = "│   ├── th_23_screenshot_manager.js\n│   ├── th_25_shortx_ui_package.js\n│   ├── .installed_manifest.json"
    text = replace_once(text, source, target, "runtime directory")
    row_anchor = "| `th_24_shortx_ui_runtime.js` | Beta 隔离的 ShortXUI 第一阶段运行时：Core、Dispatcher、Scope、Color、Metrics、Display、Shape、Diagnostics；颜色写入只通过注入的安全桥 |"
    if row_anchor in text and "| `th_25_shortx_ui_package.js` |" not in text:
        text = text.replace(
            row_anchor,
            row_anchor + "\n| `th_25_shortx_ui_package.js` | Beta 最终 ShortXUI 封装：启动成功后按真机验收顺序安装 Phase 2 至 Final R3，逐项校验压缩源码 SHA-256，失败时关闭实例并返回启动失败 |",
            1,
        )
    return text


def patch_verify_workflow(text: str) -> str:
    source = "            python3 scripts/verify_shortx_ui_windowhost.py\n"
    target = source + "            python3 scripts/finalize_shortx_ui_runtime.py --check\n"
    return replace_once(text, source, target, "verify workflow package check")


def patch_sign_workflow(text: str) -> str:
    source = (
        "      - name: Verify ShortXUI WindowHost\n"
        "        run: python3 scripts/verify_shortx_ui_windowhost.py\n"
    )
    target = (
        "      - name: Verify ShortXUI package\n"
        "        run: |\n"
        "          python3 scripts/verify_shortx_ui_windowhost.py\n"
        "          python3 scripts/finalize_shortx_ui_runtime.py --check\n"
    )
    return replace_once(text, source, target, "sign workflow package check")


def patch_scripts_readme(text: str) -> str:
    if "- `finalize_shortx_ui_runtime.py`" not in text:
        anchor = "- `generate_signed_manifest.py`\n"
        text = replace_once(
            text,
            anchor,
            anchor + "- `finalize_shortx_ui_runtime.py`：将已验收的 ShortXUI Phase 2 至 Final R3 链生成单一签名模块，并同步入口、约束和文档。\n",
            "scripts README finalizer",
        )
    return text


def patch_legacy_final_entry(text: str) -> str:
    return text.replace(
        "3d7aba0f09ebdbf5ba6d5d7b21a8d20d0097685e1a8637b21d8d3e6cb254aa1f",
        "4b2b3930f50e59066453e53303451495c198386d5539a1b4fa86aa1685f34722",
        1,
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    changed = []

    package_expected = build_package()
    if write_or_check(OUTPUT, package_expected, args.check):
        changed.append(str(OUTPUT.relative_to(ROOT)))

    targets = [
        (ENTRY, patch_entry(read_text(ENTRY))),
        (MANIFEST_GENERATOR, patch_manifest_generator(read_text(MANIFEST_GENERATOR))),
        (PREPARE_CONSTRAINTS, patch_prepare_constraints(read_text(PREPARE_CONSTRAINTS))),
        (API_RULES, patch_api_rules(read_text(API_RULES))),
        (BOUNDARIES, patch_boundaries(read_text(BOUNDARIES))),
        (PROTECTED_REPORTER, patch_protected_reporter(read_text(PROTECTED_REPORTER))),
        (ARCHITECTURE, patch_architecture(read_text(ARCHITECTURE))),
        (STRUCTURE, patch_structure(read_text(STRUCTURE))),
        (LEGACY_FINAL_ENTRY, patch_legacy_final_entry(read_text(LEGACY_FINAL_ENTRY))),
        (VERIFY_WORKFLOW, patch_verify_workflow(read_text(VERIFY_WORKFLOW))),
        (SIGN_WORKFLOW, patch_sign_workflow(read_text(SIGN_WORKFLOW))),
        (SCRIPTS_README, patch_scripts_readme(read_text(SCRIPTS_README))),
    ]
    for path, expected in targets:
        if write_or_check(path, expected, args.check):
            changed.append(str(path.relative_to(ROOT)))

    if args.check:
        print("ShortXUI final package is current")
    elif changed:
        print("Updated ShortXUI final package:")
        for item in changed:
            print(" - " + item)
    else:
        print("ShortXUI final package already current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
